#!/usr/bin/env sh

export ROOT_DISPLAY_UUID='41D3C12A-1527-D16E-F44E-90028431FC4E'
export PATH="$HOME/src/yabai/bin:$PATH"

sudo yabai --load-sa
yabai -m signal --add \
  label=reload_sa \
  event=dock_did_restart \
  action="sudo yabai --load-sa"

yabai -m config debug_output on


# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus
yabai -m config display_sort_order           horizontal
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85
yabai -m config split_ratio                  0.68
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

yabai -m config insert_feedback_color 0xaad75f5f

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   2

yabai -m rule --add label=system-prefs app="^System Preferences$" layer=above manage=off
yabai -m rule --add label=renoise-above app="^Renoise$" layer=above manage=off
yabai -m rule --add label=renoise-normal-xrns app="^Renoise$" title=".xrns$" layer=normal manage=off
yabai -m rule --add label=renoise-normal-init app="^Renoise$" title="^Renoise" layer=normal manage=off
yabai -m rule --add label=gimp app="^GIMP" layer=normal manage=off
yabai -m rule --add label=reminders app="^Reminders" layer=above manage=off
yabai -m rule --add label=live-export app="^Live$" title="Export" manage=off
yabai -m rule --add label=electron-specs app="^Electron$" manage=off
yabai -m rule --add label=processing-runner app="^Runner$" manage=off
yabai -m rule --add label=tk-runner app="^Python$" manage=off
yabai -m rule --add label=demo title="^Demo$" manage=off
yabai -m rule --add label=iina app="^IINA$" manage=off

# yabai -m rule --add app="^Live$" manage=off

yabai -m rule --add title="Preferences" layer=above manage=off

~/.local/bin/spaces init

# yabai -m rule --add app="^Discord$" space=7
# yabai -m rule --add app="^Firefox$" space=2

echo "yabai configuration loaded.."
